name: template_cod
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  floor: ^1.4.1
  json_annotation: ^4.8.0
  floor_generator: ^1.4.1
  build_runner: ^2.3.3
  retrofit: ^3.3.1
  logger: ^1.1.0
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  web_socket_channel: ^2.3.0
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  retrofit_generator: any


flutter:
  uses-material-design: true
  assets:
    - assets/images/img.png
    - assets/images/img.jpeg
